config/routes.rb
Quiz::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/publish' => 'publishing#publish', :as => :portal_publish, :method => :get

  match '/responses/run' => 'responses#run', :as => :responses_run, :method => :get
  resources :responses

  root :to => "responses#index"

end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :answer

  has_one :run
end

app/models/run.rb
class Run < ActiveRecord::Base
  attr_accessible :key, :response_id, :return_url

  belongs_to :response

  def self.key_for(domain, id)
    domain && id ? "#{domain}#{id}" : "#{SecureRandom.uuid}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:concord_portal]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :token

  def self.find_for_concord_portal_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      email = auth.info.email || "#{Devise.friendly_token[0,20]}@example.com"
      user = User.create(provider:auth.provider,
                         uid:     auth.uid,
                         email:   email,
                         password:Devise.friendly_token[0,20]
                        )
    end
    user.token = auth.credentials.token
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # override devise's built in method so we can go back to the path
  # from which authentication was initiated
  def after_sign_in_path_for(resource)
    session.delete(:auth_return_url) || request.env['omniauth.origin'] || stored_location_for(resource) || signed_in_root_path(resource)
  end
end

app/controllers/publishing_controller.rb
class PublishingController < ApplicationController
  def publish
    activity = {
      "name" => "Simple Quiz",
      "description" => "A simple, one-question quiz.",
      "url" => root_url,
      "create_url" => responses_run_url
    }

    page = {
      "name" => "Response",
      "elements" => [
        {
          "type" => "open_response",
          "id" => "1",
          "prompt" => "Why is the sky blue?"
        }
      ]
    }

    section = {
      "name" => "Simple Quiz Section",
      "pages" => [page]
    }

    activity["sections"] = [section]
    portal_url = (ENV['CONCORD_PORTAL_URL'] || "http://localhost:3000") + '/external_activities/publish'
    bearer_token = 'Bearer %s' % current_user.token
    response = HTTParty.post(portal_url, :body => activity.to_json, :headers => {"Authorization" => bearer_token, "Content-Type" => 'application/json'})
    if response.code == 201
      # success
      flash[:notice] = "Successfully published to portal: #{response.headers["Location"]}"
    else
      # error
      flash[:error] = "Failed to publish to portal!"
    end
    redirect_to root_path
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responses }
    end
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/new
  # GET /responses/new.json
  def new
    @response = Response.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(params[:response])

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render json: @response, status: :created, location: @response }
      else
        format.html { render action: "new" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responses/1
  # PUT /responses/1.json
  def update
    @response = Response.find(params[:id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        if @response.run && @response.run.return_url
          # send the data back to the portal
          data = [{
            "type" =>        "open_response",
            "question_id" => "1",
            "answer" =>      params[:response][:answer]
          }]
          bearer_token = 'Bearer %s' % current_user.token
          HTTParty.post(@response.run.return_url, :body => data.to_json, :headers => {"Authorization" => bearer_token, "Content-Type" => 'application/json'})
        end
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response = Response.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  def run
    if current_user.nil?
      session[:auth_return_url] = request.url
      redirect_to user_omniauth_authorize_path(:concord_portal)
    else
      domain = params[:domain]
      external_id = params[:externalId]
      return_url = params[:returnUrl]

      run = Run.find_or_create_by_key(Run.key_for(domain, external_id))
      run.return_url = return_url
      run.response = Response.create unless run.response_id
      run.save

      redirect_to edit_response_path(run.response)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def concord_portal
    omniauth = request.env["omniauth.auth"]
    @user = User.find_for_concord_portal_oauth(omniauth, current_user)
    sign_in_and_redirect @user, :event => :authentication
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="hmenu">
  <%= render 'users/menu/registration_items' %>
  <%= render 'users/menu/login_items' %>
  <%= render 'users/menu/publish_items' %>
</ul>
<p><%= flash[:notice] %></p>
<p style="color: red;"><%= flash[:error] %></p>
<%= yield %>

</body>
</html>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Why is the sky blue?

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.answer %></td>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

 Why is the sky blue?

<p>
  <b>Answer:</b>
  <%= @response.answer %>
</p>


<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
  <li>
  <%= link_to("Sign in with Concord Portal", user_omniauth_authorize_path(:concord_portal)) %>
  </li>
<% end %>

app/views/users/menu/_publish_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Publish to Concord Portal', portal_publish_path) %>
  </li>
<% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>